import Achievement from "./Achievement";

export default function Achievements() {
  return (
    <div className="flex flex-col items-start md:items-center p-4 pt-16 sm:p-16 bg-neutral-100 dark:bg-neutral-900">
      <h1 className="self-center text-center font-bold text-3xl mb-10">Achievements</h1>
      <Achievement date="28-05-2024" title="Central exam VWO French" description="I am excited to share that I have successfully completed the central exam in French at the VWO level with a score of 9,4/10! This achievement reflects my strong understanding of the French language. Preparing for this exam required a lot of dedication and focus. Reaching this milestone is a significant accomplishment. This success gives me confidence as I continue to explore new opportunities and challenges in my educational journey. I was allowed to do this exam one year earlier, since my knowledge of the French language exceeded the expected level on VWO." />
      <Achievement date="17-05-2024" title="DELE exam B1 Spanish" description="I am happy to share that I have successfully passed the DELE B1 exam in Spanish with a score of 73,75/10! This milestone is a significant achievement in my journey to becoming proficient in Spanish, demonstrating my ability to handle everyday conversations and written communication with ease. Achieving this goal took a lot of perseverance and hard work, and I am proud of the efforts I have made." />
      <Achievement date="16-04-2024" title="Award ceremony writing contest French: 2nd place" description="I am honored to share that I earned 2nd place in a writing contest focused on the future of the European Union, where I wrote a dissertation in French! This achievement is particularly meaningful to me, as it reflects both my passion for the topic and my growing proficiency in the French language. Competing against many talented individuals, I am proud to have my ideas and writing recognized on such a significant subject. This experience has inspired me to continue sharpen my skills and exploring important global issues through writing." />
      <Achievement date="16-03-2024" title="DELF exam B2 French" description="I am thrilled to announce that I have successfully passed the DELF B2 exam in French with a score of 74,5/100! This accomplishment marks a significant step forward in my language learning journey, showcasing my advanced proficiency in French. The B2 certification is a testament to my ability to communicate fluently and effectively in complex situations, both in writing and speaking. Reaching this level has required a lot of hard work and dedication, and I am incredibly proud of the progress I have made." />
      <Achievement date="10-06-2023" title="DELF exam B1 French" description="I am proud to share that I have successfully passed the DELF B1 exam in French with a score of 89/100! This achievement represents a significant milestone in my journey to mastering the French language. Earning this certification has not only strengthened my communication skills in listening, speaking, reading, and writing, but it also demonstrates my commitment to learning and growing. It feels very rewarding to see my hard work and dedication pay off, and I am excited about the new opportunities this opens up for me, both personally and professionally." />
      <Achievement date="28-03-2023" title="U-talent masterclass Albert Camus" description="I participated in this masterclass at the University of Utrecht, dedicated to the renowned French author Albert Camus, with a particular focus on his work, The Stranger. The session involved a detailed analysis of the novel and its historical context, enriching my understanding of his philosophical and literary contributions. Engaging in discussions with fellow students allowed me to exchange ideas and gain deeper insights into the study of his work, further enhancing my appreciation for his literary legacy and the broader existential themes he explored." />
      <Achievement date="10-02-2023" title="U-talent masterclass linguistics" description="During this masterclass at the University of Utrecht, I delved into the complexities of various languages and their underlying patterns. The experience was both intellectually stimulating and personally rewarding. As I explored the campus and interacted with fellow participants who shared my enthusiasm for linguistics, I found myself immersed in rich discussions and new perspectives. The opportunity to study the nuances of language structures and to connect with like-minded individuals was truly inspiring, enhancing both my academic knowledge and my appreciation for the diverse world of languages." />
    </div>
  )
}
